name: Regression Test CI

on:
  push:
    branches:
      - main
      - testing-regression

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: xplorra

    services:
      mysql:
        image: mysql:8

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: xplorra

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Import Database
        run: |
          mysql -h 127.0.0.1 -u root -proot xplorra < xplorra.sql

      - name: Run Tests
        run: npx jest --forceExit